usuario_usuario:
    resource: "@UsuarioBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario

usuario_homepage:
    path:     /
    defaults: { _controller: UsuarioBundle:Default:index }
